* Readme for Jupyter Notebooks

Jupyter notebooks in R, Common Lisp (SBCL) and Python

** Common Lisp

https://github.com/stephen-rowan/Jupyter_Notebooks/tree/master/Common-Lisp

Exercises taken from [[http://www.gigamonkeys.com/book/][Practical Common Lisp]] by Peter Seibel.

** Data Science for Business

Notes and exercises from [[http://data-science-for-biz.com/DSB/Home.html][Data Science for Business]] by Foster Provost and Tom Fawcett.

** Datacamp

Datacamp exercises.

** Graphs (Python)

Playing with graphs (diagraphs) and graphviz in Python.

** Introduction to Probability and Data (R)

Exercises and notes from the Coursera course "Introduction to Probability and Data".

** JSON (R)

These workbooks use the R statistical language to extract data from websites using Omeka's JSON API.

** Lambda Calculus (Haskell)

Rough notes and exercises in Haskell.

** Linear Algebra (Python)

Linear Algebra exercises.

** Probabilistic Programming and Bayesian Methods for Hackers (Python)

Exercises from the book [[http://nbviewer.jupyter.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Ch1_Introduction_PyMC2.ipynb][Probabilistic Programming and Bayesian Methods for Hackers]]

** Tensor Flow (Python)

Basic Tensor Flow exercises in Python.



